apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Release.Name }}-nginx-server
  name: {{ .Release.Name }}-nginx-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx-server
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
         - mountPath: "/usr/share/nginx/html"
           name: task-pv-storage
      volumes:
       - name: task-pv-storage
         hostPath:
             path: {{ $.Chart.Name }}/content
